### ISSUE TITLE
Padrão de Ambiente no Projeto

### ISSUE THREAD

**Issue by lucascorreaa** [Leticia-Emily-Moraes/projeto-fauna#5]
Criar padrão de branch no projeto:

develop - ambiente de desenvolvimento
qas - ambiente de teste
prod - ambiente de deploy final

As branch de novas features, fix, etc... Quando for fazer merger é para a develop, quando a develop estiver rodando liso depois de estressar de teste, ai é PR da develop para qas, e qas para prod.

* atualmente a sua principal é a main, pode renomear ela pra develop e criar as outras *

**Comment by Leticia-Emily-Moraes** [comment]
seguindo a alteração proposta, fica a seguinte estrutura
![Captura de tela 2024-07-24 154257](https://github.com/user-attachments/assets/2a5ba87d-a0dd-4f6d-af34-6281ecbba4f2)
tem alguma sugestão de como fazer os teste?

**Comment by lucascorreaa** [comment]
Você pode identificar as branch, pelo próprio GitHub, e depois que criar uma feature ou resolver um bug, fazer um fluxo:

Realizar ajuste ou implementação, criando um branch para ela, após testar, realizar esse fluxo, manual, até criar sua pipeline, exemplo:

fix/example => develop

develop => qas

qas => prod
