### ISSUE TITLE
Estrutura do projeto no GitHub

### ISSUE THREAD

**Issue by lucascorreaa** [Leticia-Emily-Moraes/projeto-fauna#6]
Atualmente tem uma pasta com o projeto dentro e um README.

Mas o padrão de repositórios não é ter pasta que leva até o projeto pq atrapalha o desenvolvimento, tqer que da cd para realizar comandos dentro.

Então a estrutura padrão seria assim:

<img width="329" alt="image" src="https://github.com/user-attachments/assets/528ae828-be58-4fdf-8813-d9cb59fe47b8">

Outro ponto:

Para que serve esse arquivo %ProgramData%, caso não tenha utilização, remover ele.

**Comment by Leticia-Emily-Moraes** [comment]
Alteração feita para um padrão
![Captura de tela 2024-07-24 153252](https://github.com/user-attachments/assets/bae5a2bd-f695-42d8-a384-c959fc3a7580)
